language: go
sudo: false
go:
- 1.11.x

before_install:

- export GO111MODULE=on
- go get -t -v ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)